
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - "Django_SECRET_KEY=django-insecure-8#k%6&f@zx=z5tuary1_!s%ypqk_i7kacc86hkd5g26ox#h(uf"
      - "DJANGO_DEBUG=True"

    