# Generated by Django 5.1.4 on 2025-01-20 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='actors_images')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField()),
                ('biography', models.TextField()),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('date_of_birth_place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livetv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='livetv_images')),
                ('star_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(upload_to='film_images')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(related_name='films', to='film.actors')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='film.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('stars', models.CharField(choices=[('1', 'خیلی بد'), ('2', 'بد'), ('3', 'عادی'), ('4', 'خوب'), ('5', 'عالی')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('download_link_480', models.URLField(blank=True)),
                ('download_link_720', models.URLField(blank=True)),
                ('download_link_1080', models.URLField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='film.film')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(upload_to='serirs_images')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(related_name='series', to='film.actors')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='film.genre')),
            ],
        ),
    ]
