# Generated by Django 5.1.4 on 2025-01-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='series',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='film.genre'),
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(related_name='series', to='film.genre'),
        ),
    ]
