# Generated by Django 5.1.4 on 2025-01-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_remove_film_genre_remove_series_genre_film_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='download_link_1080',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='download_link_480',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='download_link_720',
        ),
        migrations.AddField(
            model_name='film',
            name='download_link_1080',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='download_link_480',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='download_link_720',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='series',
            name='download_link_1080',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='series',
            name='download_link_480',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='series',
            name='download_link_720',
            field=models.URLField(blank=True),
        ),
    ]
